version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: profilehub-postgres
    environment:
      POSTGRES_DB: profilehub
      POSTGRES_USER: profilehub_user
      POSTGRES_PASSWORD: profilehub_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - profilehub-network

  redis:
    image: redis:7-alpine
    container_name: profilehub-redis
    ports:
      - "6379:6379"
    networks:
      - profilehub-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: profilehub-backend
    environment:
      # Opcional: sobrescrever segredo JWT em produção
      - JWT_SECRET=${JWT_SECRET:-TXlWZXJ5U2VjdXJlSldUU2VjcmV0S2V5MzJCeXRlc0xvbmdGb3JQcm9kdWN0aW9uVXNl}
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    networks:
      - profilehub-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: profilehub-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - profilehub-network

networks:
  profilehub-network:
    driver: bridge

volumes:
  postgres-data:


